module Shards
  module Compliance
    module HtmlTemplate
      def self.render(data : ReportData) : String
        String.build do |html|
          html << "<!DOCTYPE html>\n"
          html << "<html lang=\"en\">\n<head>\n"
          html << "<meta charset=\"UTF-8\">\n"
          html << "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
          html << "<title>Compliance Report - #{escape_html(data.project.name)}</title>\n"
          html << "<style>\n#{CSS}\n</style>\n"
          html << "</head>\n<body>\n"

          # Header
          html << "<header>\n"
          html << "<h1>Supply Chain Compliance Report</h1>\n"
          html << "<div class=\"report-meta\">\n"
          html << "<span class=\"project\">#{escape_html(data.project.name)} v#{escape_html(data.project.version)}</span>\n"
          html << "<span class=\"date\">Generated: #{data.generated_at.to_rfc3339}</span>\n"
          html << "<span class=\"generator\">#{escape_html(data.generator)}</span>\n"
          html << "</div>\n</header>\n"

          # Summary
          html << "<section class=\"summary\">\n"
          html << "<h2>Executive Summary</h2>\n"
          html << "<div class=\"status-badge #{data.summary.overall_status}\">#{data.summary.overall_status.upcase}</div>\n"
          html << "<table class=\"metrics\">\n"
          html << "<tr><td>Total Dependencies</td><td>#{data.summary.total_dependencies}</td></tr>\n"
          html << "<tr><td>Direct Dependencies</td><td>#{data.summary.direct_dependencies}</td></tr>\n"
          html << "<tr><td>Transitive Dependencies</td><td>#{data.summary.transitive_dependencies}</td></tr>\n"
          html << "<tr><td>License Compliance</td><td>#{data.summary.license_compliance}</td></tr>\n"
          html << "<tr><td>Policy Compliance</td><td>#{data.summary.policy_compliance}</td></tr>\n"
          html << "</table>\n</section>\n"

          # SBOM section
          if sbom = data.sections.sbom
            html << render_sbom_section(sbom)
          end

          # Integrity section
          if integrity = data.sections.integrity
            html << render_integrity_section(integrity)
          end

          # Attestation
          if att = data.attestation
            html << "<section class=\"attestation\">\n"
            html << "<h2>Attestation</h2>\n"
            html << "<p><strong>Reviewer:</strong> #{escape_html(att.reviewer)}</p>\n"
            html << "<p><strong>Reviewed:</strong> #{att.reviewed_at.to_rfc3339}</p>\n"
            html << "</section>\n"
          end

          html << "<footer><p>Generated by #{escape_html(data.generator)}</p></footer>\n"
          html << "<script>\n#{JS}\n</script>\n"
          html << "</body>\n</html>"
        end
      end

      private def self.render_sbom_section(sbom : JSON::Any) : String
        String.build do |html|
          html << "<section class=\"sbom\">\n"
          html << "<h2 class=\"section-header\">Software Bill of Materials</h2>\n"
          html << "<div class=\"section-content\">\n"
          if pkgs = sbom["packages"]?
            html << "<table>\n<thead><tr><th>Package</th><th>Version</th><th>License</th><th>Download</th></tr></thead>\n<tbody>\n"
            pkgs.as_a.each do |pkg|
              html << "<tr>"
              html << "<td>#{escape_html(pkg["name"]?.try(&.as_s) || "")}</td>"
              html << "<td>#{escape_html(pkg["versionInfo"]?.try(&.as_s) || "")}</td>"
              html << "<td>#{escape_html(pkg["licenseDeclared"]?.try(&.as_s) || "")}</td>"
              html << "<td>#{escape_html(pkg["downloadLocation"]?.try(&.as_s) || "")}</td>"
              html << "</tr>\n"
            end
            html << "</tbody></table>\n"
          end
          html << "</div>\n</section>\n"
        end
      end

      private def self.render_integrity_section(integrity : JSON::Any) : String
        String.build do |html|
          html << "<section class=\"integrity\">\n"
          html << "<h2 class=\"section-header\">Dependency Integrity</h2>\n"
          html << "<div class=\"section-content\">\n"
          all_ok = integrity["all_verified"]?.try(&.as_bool)
          html << "<p class=\"status #{all_ok ? "pass" : "fail"}\">All verified: #{all_ok}</p>\n"
          if deps = integrity["dependencies"]?
            html << "<table>\n<thead><tr><th>Dependency</th><th>Version</th><th>Verified</th><th>Reason</th></tr></thead>\n<tbody>\n"
            deps.as_a.each do |dep|
              verified = dep["verified"]?.try(&.as_bool) || false
              html << "<tr class=\"#{verified ? "pass" : "warn"}\">"
              html << "<td>#{escape_html(dep["name"]?.try(&.as_s) || "")}</td>"
              html << "<td>#{escape_html(dep["version"]?.try(&.as_s) || "")}</td>"
              html << "<td>#{verified}</td>"
              html << "<td>#{escape_html(dep["reason"]?.try(&.as_s) || "")}</td>"
              html << "</tr>\n"
            end
            html << "</tbody></table>\n"
          end
          html << "</div>\n</section>\n"
        end
      end

      private def self.escape_html(str : String) : String
        str.gsub("&", "&amp;").gsub("<", "&lt;").gsub(">", "&gt;").gsub("\"", "&quot;")
      end

      CSS = <<-'CSS'
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 1200px; margin: 0 auto; padding: 2rem; color: #333; }
        header { border-bottom: 2px solid #e0e0e0; padding-bottom: 1rem; margin-bottom: 2rem; }
        h1 { font-size: 1.8rem; color: #1a1a2e; }
        h2 { font-size: 1.3rem; margin: 1.5rem 0 1rem; color: #16213e; cursor: pointer; }
        .report-meta { display: flex; gap: 2rem; margin-top: 0.5rem; color: #666; font-size: 0.9rem; }
        .status-badge { display: inline-block; padding: 0.4rem 1rem; border-radius: 4px; font-weight: bold; color: white; text-transform: uppercase; }
        .status-badge.pass { background: #28a745; }
        .status-badge.fail { background: #dc3545; }
        .status-badge.action_required { background: #ffc107; color: #333; }
        table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
        th, td { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #e0e0e0; }
        th { background: #f8f9fa; font-weight: 600; }
        tr.pass td:nth-child(3) { color: #28a745; }
        tr.warn td:nth-child(3) { color: #ffc107; }
        .summary { margin-bottom: 2rem; }
        .metrics { max-width: 400px; }
        section { margin-bottom: 2rem; }
        .section-content { margin-left: 1rem; }
        .attestation { border-top: 2px solid #e0e0e0; padding-top: 1rem; }
        footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e0e0e0; color: #999; font-size: 0.85rem; }
        @media print { .section-header { cursor: default; } body { max-width: none; } }
      CSS

      JS = <<-'JS'
        document.querySelectorAll('.section-header').forEach(function(h) {
          h.addEventListener('click', function() {
            var content = h.nextElementSibling;
            if (content) { content.style.display = content.style.display === 'none' ? '' : 'none'; }
          });
        });
      JS
    end
  end
end
